### ISSUE TITLE
Fix the CSRF token usage in React powered forms

### ISSUE THREAD

**Issue by orlando** [debtcollective/fundraising#18]
**What:** Fix the CSRF token usage in React powered forms

**Why:** We are having problems with CSRF tokens not working in React based forms. Right now there's code that implements how React is getting this token, but it is also generating the CSRF token manually, something that should be handled by Rails

**How:**

- Remove code to generate and inject CSRF and use Rails implementation instead.
- Make React powered forms work correctly.

**Comment by castrolem** [comment]
@orlando let me know if you would like to pair on this one.
