### ISSUE TITLE
Remove dry-validation gem

### ISSUE THREAD

**Issue by orlando** [debtcollective/fundraising#21]
**What:** Remove dry-validation gem

**Why:** We are having problems in the latest 5.x Rails version and this gem. This is only used to validate configuration and is not something we want to invest time to fix it.

**How:**

- Remove dry-validation gem
- Remove code related to dry-validation gem

**Comment by castrolem** [comment]
We're using this gem a lot for verifications during runtime and also at certain points depending on the controller and some error messages.

Therefore we cannot just remove it.

There's an [article that sums up the path to upgrade](https://www.morozov.is/2019/05/31/upgrading-dry-gems.html) from version `0.13` to the latest `1.x` but it's not an easy task or is rather complex and it might not be necessary for now.

**Comment by castrolem** [comment]
Won't do, since it's not worth it to upgrade right this gem. Mainly the setup changes but the validations stay the same, so it would just be around separating the concerns as the new version of the gem requires and modifying all the setup for it.
